title: Graficas Interactivas
logo: /Images/embalse.jpg
description: Graficas interactivas para el analisis de la informacion. 
show_downloads: true
author: Some Person
favicon: favicon.ico
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

